version: '3.1'

services:
  cron:
    image: 127.0.0.1:5000/symbols_cron
    build:
      context: .
      dockerfile: Dockerfile-cron
    volumes:
      - ./stocksymbols:/home/app/stocksymbols
      - ./cron.py:/home/app/cron.py
  api:
    image: 127.0.0.1:5000/symbols_api
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - ./stocksymbols:/home/app/stocksymbols
      - ./main.py:/home/app/main.py
    ports:
      - 7777:7777

networks:
  default:
    external:
      name: svc-overlay-network
