FROM python:3.8.6-slim-buster

WORKDIR /home/app

#COPY stocksymbols ./stocksymbols
#COPY main.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

CMD uvicorn main:app --host 0.0.0.0 --port 7777 --reload