version: '3.1'

services:
  cron:
    image: 127.0.0.1:5000/symbols_cron
    build:
      context: .
      dockerfile: Dockerfile-cron
    volumes:
      - ./stocksymbols:/home/app/stocksymbols
      - ./cron.py:/home/app/cron.py

networks:
  default:
    external:
      name: svc-overlay-network
